// Code generated by flatc. DO NOT EDIT.
// Source: examples/schemas/player_position.fbs

package example

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// PlayerPosition represents a 3D position with x, y, z float32 fields.
type PlayerPosition struct {
	_tab flatbuffers.Table
}

// GetRootAsPlayerPosition deserializes a PlayerPosition from a byte buffer.
func GetRootAsPlayerPosition(buf []byte, offset flatbuffers.UOffsetT) *PlayerPosition {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerPosition{}
	x.Init(buf, n+offset)
	return x
}

// Init initializes the PlayerPosition from a raw buffer and position.
func (rcv *PlayerPosition) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

// Table provides access to the underlying flatbuffers.Table.
func (rcv *PlayerPosition) Table() flatbuffers.Table {
	return rcv._tab
}

// X returns the x coordinate.
func (rcv *PlayerPosition) X() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

// Y returns the y coordinate.
func (rcv *PlayerPosition) Y() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

// Z returns the z coordinate.
func (rcv *PlayerPosition) Z() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

// PlayerPositionStart begins building a PlayerPosition FlatBuffer.
func PlayerPositionStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}

// PlayerPositionAddX adds the x field to the PlayerPosition being built.
func PlayerPositionAddX(builder *flatbuffers.Builder, x float32) {
	builder.PrependFloat32Slot(0, x, 0.0)
}

// PlayerPositionAddY adds the y field to the PlayerPosition being built.
func PlayerPositionAddY(builder *flatbuffers.Builder, y float32) {
	builder.PrependFloat32Slot(1, y, 0.0)
}

// PlayerPositionAddZ adds the z field to the PlayerPosition being built.
func PlayerPositionAddZ(builder *flatbuffers.Builder, z float32) {
	builder.PrependFloat32Slot(2, z, 0.0)
}

// PlayerPositionEnd finishes building the PlayerPosition and returns its offset.
func PlayerPositionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
